// ===================================================================================
// render.js — Three.js scene, hand-rolled orbit camera (r128 has no OrbitControls),
// mesh construction from a Poly (arbitrary convex polygon faces, fan-triangulated),
// and the pole-contraction morph animation.
// ===================================================================================
(function (global) {
  'use strict';

  // Faces are classified by actual shape, not just side count:
  //   C(n) faces: triangle / rhombus (all 4 sides equal, or trying to be) / trapezoid
  //     (including skewed quads from a pole-face-adjacency defect) / floret pentagon
  //   fullerene faces (pre-contraction view): hexagon / pole face — the pole face is
  //     whatever polygon a valid fullerene's pole gets contracted from (pentagon for
  //     icosahedral symmetry, quad for octahedral, triangle for tetrahedral), so in
  //     fullerene context ANY non-hexagon face is unambiguously a pole face, regardless
  //     of its side count.
  // The one error marker left is a leftover 6-sided face in C(n) context ("isolated
  // hexagons" isomers — an admissible C(n) never has one). A "non-isolated pole faces"
  // defect is flagged differently: as a highlighted edge in the fullerene view (see
  // buildEdgeGeometry/setPoly's highlightEdges param), not by recoloring faces — the C(n)
  // faces around it still get their normal classification, just possibly less regular.
  const FACE_COLORS = {
    triangle: 0xf2c94c,        // yellow
    rhombus: 0xd6493a,         // red
    trapezoid: 0x4caf6d,       // green
    floretPentagon: 0x3f7fd1,  // blue
    fullereneHexagon: 0xf7f7f2,  // white
    fullerenePoleFace: 0x1a1a1a, // black
    error: 0xd633c4              // magenta
  };
  const EDGE_QUAD_COLOR = 0x999488; // grey — the physical "wall" face opened up along an
                                     // original edge during the dual morph (see below)
  const EDGE_COLOR = 0x3a352c;
  const EDGE_HIGHLIGHT_COLOR = 0xd633c4; // magenta, marks a pole-face adjacency edge
  const POLE_COLOR = 0x24211b;

  // "Colour by symmetry" palette (Stella-style), reused for both face-orbit colors and
  // symmetry-axis rods: rank 0 (largest-area face orbit, or the highest-order axis family)
  // gets the first color, rank 1 the next, etc. Defined by HSL rather than hand-picked hex
  // so hue/lightness/saturation can be tuned independently -- red/orange/yellow/brown
  // necessarily share the 0-50° hue band (that IS what makes them read as those names), so
  // they're pulled apart by lightness+saturation instead; blue and cyan are pushed a full
  // 54° apart in hue on top of a lightness difference, since two saturated colors only ~30°
  // apart (an earlier version had them there) read as near-identical on a lit 3D surface.
  function hsl(h, s, l) { return new THREE.Color().setHSL(h / 360, s, l).getHex(); }
  const SYMMETRY_PALETTE = [
    hsl(6, 0.62, 0.52),   // red
    hsl(232, 0.62, 0.52), // blue
    hsl(46, 0.80, 0.63),  // yellow
    hsl(125, 0.50, 0.45), // green
    hsl(178, 0.70, 0.50), // cyan
    hsl(308, 0.60, 0.50), // magenta
    hsl(30, 0.72, 0.52),  // orange
    hsl(22, 0.38, 0.34)   // brown
  ];
  const SYMMETRY_PALETTE_HUES = [6, 232, 46, 125, 178, 308, 30, 22];
  const GOLDEN_ANGLE = 137.508;
  const SYM_MIN_HUE_GAP = 25;              // degrees -- only ~floor(360/25)=14 hues can ever
                                            // satisfy this gap around one full circle
  const SYM_HUES_PER_TIER = Math.floor(360 / SYM_MIN_HUE_GAP);
  // Cycled through once a tier's ~14 hue slots are used up, so a very-low-symmetry solid
  // (e.g. C1 -- every face its own orbit) can still get *some* separation between classes
  // that share a hue: lightness/saturation differs per tier even when hue repeats.
  const SYM_TIERS = [{ s: 0.62, l: 0.50 }, { s: 0.55, l: 0.70 }, { s: 0.78, l: 0.34 }];
  function hueDist(a, b) { const d = Math.abs(a - b) % 360; return Math.min(d, 360 - d); }

  // Beyond the 8 named colors, additional classes are generated by walking the hue wheel at
  // the golden angle -- quasi-uniform, so it keeps spreading -- preferring candidates
  // SYM_MIN_HUE_GAP away from every hue already used in the current tier (falling back to
  // the least-bad candidate found in a bounded search, never an unbounded one: a *fixed*
  // minimum-gap requirement can only ever be satisfied by a bounded number of hues around
  // one circle, so demanding it forever, unconditionally, is an infinite loop waiting to
  // happen the moment a solid needs more classes than that -- confirmed the hard way on an
  // n=41 C1 (fully asymmetric) Catalan-like solid, whose ~40+ singleton face-orbits froze
  // the tab solid). Results are cached (colorForSymmetryRank is called once per face, and
  // a low-symmetry solid can have dozens of them) so the search only ever runs once per
  // distinct extra rank actually used, not once per call.
  const _extraHueCache = [];
  function extraHueFor(extraIdx) {
    while (_extraHueCache.length <= extraIdx) {
      const idx = _extraHueCache.length;
      const tier = Math.floor(idx / SYM_HUES_PER_TIER);
      const tierStart = tier * SYM_HUES_PER_TIER;
      const huesInTier = _extraHueCache.slice(tierStart);
      const against = tier === 0 ? SYMMETRY_PALETTE_HUES.concat(huesInTier) : huesInTier;
      let best = 0, bestScore = -1;
      for (let i = 0; i < 4 * SYM_HUES_PER_TIER; i++) {
        const hue = (i * GOLDEN_ANGLE) % 360;
        const minDist = against.length ? Math.min(...against.map(h => hueDist(h, hue))) : 360;
        if (minDist >= SYM_MIN_HUE_GAP) { best = hue; bestScore = minDist; break; }
        if (minDist > bestScore) { bestScore = minDist; best = hue; }
      }
      _extraHueCache.push(best);
    }
    return _extraHueCache[extraIdx];
  }

  function colorForSymmetryRank(rank) {
    if (rank < SYMMETRY_PALETTE.length) return SYMMETRY_PALETTE[rank];
    const extraIdx = rank - SYMMETRY_PALETTE.length;
    const tier = Math.floor(extraIdx / SYM_HUES_PER_TIER);
    const style = SYM_TIERS[Math.min(tier, SYM_TIERS.length - 1)];
    const hue = extraHueFor(extraIdx);
    return new THREE.Color().setHSL(hue / 360, style.s, style.l).getHex();
  }

  // Which face-context a poly is being viewed in must be passed explicitly rather than
  // inferred from its faces — a fullerene has only pole-face/hexagon faces, but a C(n)
  // (specifically an "invalid: isolated hexagons" one) can ALSO contain a hexagon face,
  // so hexagon-presence alone can't tell the two apart. In C(n) context every hexagon face
  // IS an isolated one (an admissible C(n) never has any); in fullerene context only the
  // specific faces named in isolatedHexFaceIndices (by index into poly.faces) are.
  // highlightIsolatedHex is a toggle: off, isolated hexagons read as plain white in both
  // contexts instead of the magenta error color.
  function classifyFace(poly, face, faceIndex, isFullereneCtx, isolatedHexFaceIndices, forceRhombusQuads) {
    const n = face.length;
    if (isFullereneCtx) {
      if (n !== 6) return 'fullerenePoleFace';
      const isIsolated = !!(isolatedHexFaceIndices && isolatedHexFaceIndices.has(faceIndex));
      return (isIsolated && toggles.highlightIsolatedHex) ? 'error' : 'fullereneHexagon';
    }
    if (n === 6) return toggles.highlightIsolatedHex ? 'error' : 'fullereneHexagon'; // isolated-hexagon survivor
    if (n === 5) return 'floretPentagon';
    if (n === 3) return 'triangle';
    if (n === 4) {
      if (forceRhombusQuads) return 'rhombus';
      // A quad "trying to be" a rhombus reads as one even with modest deviation — these
      // isomers aren't always fully converged to canonical form, so a strict tolerance
      // would misclassify a near-rhombus as a trapezoid.
      const pts = face.map(vi => poly.verts[vi]);
      const sides = [0, 1, 2, 3].map(i => pts[i].distanceTo(pts[(i + 1) % 4]));
      const avg = sides.reduce((a, b) => a + b, 0) / 4;
      const allEqual = sides.every(s => Math.abs(s - avg) < avg * 0.12);
      return allEqual ? 'rhombus' : 'trapezoid';
    }
    return 'fullereneHexagon';
  }

  let scene, camera, rendererGL, canvas;
  let world; // group holding the polyhedron + edges + poles
  let faceMesh = null, edgeLines = null, highlightLines = null, poleGroup = null, sphereMesh = null, axisGroup = null;
  let orbitQuat = new THREE.Quaternion();
  let dragging = false, lastX = 0, lastY = 0;
  let autoRotate = true, userInteracted = false, idleTimer = null;
  let camDistance = 3.4;
  let toggles = { color: true, symmetryColor: false, edges: true, sphere: false, poles: false, spin: false, highlightIsolatedHex: true, axes: false };

  // Returns true on success, false if a WebGL context couldn't be created (e.g. WebGL
  // disabled in the browser) — THREE.WebGLRenderer throws in that case rather than
  // failing gracefully, so the caller needs a way to find out without a crash.
  function init(canvasEl) {
    canvas = canvasEl;
    try {
      rendererGL = new THREE.WebGLRenderer({ canvas, antialias: true });
    } catch (e) {
      return false;
    }

    scene = new THREE.Scene();
    scene.background = new THREE.Color(0xf7f6f3);

    camera = new THREE.PerspectiveCamera(38, 1, 0.1, 100);
    camera.position.set(0, 0, camDistance);

    rendererGL.setPixelRatio(Math.min(window.devicePixelRatio || 1, 2));

    world = new THREE.Group();
    scene.add(world);

    const key = new THREE.DirectionalLight(0xffffff, 0.9);
    key.position.set(3, 4, 5);
    scene.add(key);
    const fill = new THREE.DirectionalLight(0xffffff, 0.45);
    fill.position.set(-4, -2, -3);
    scene.add(fill);
    scene.add(new THREE.AmbientLight(0xffffff, 0.55));

    const sphereGeo = new THREE.SphereGeometry(1, 128, 96);
    const sphereMat = new THREE.MeshBasicMaterial({ color: 0x18232e, transparent: true, opacity: 0.4, depthWrite: false });
    sphereMesh = new THREE.Mesh(sphereGeo, sphereMat);
    sphereMesh.visible = false;
    world.add(sphereMesh);

    poleGroup = new THREE.Group();
    world.add(poleGroup);

    axisGroup = new THREE.Group();
    axisGroup.visible = toggles.axes;
    world.add(axisGroup);

    resize();
    window.addEventListener('resize', resize);

    canvas.addEventListener('mousedown', onDown);
    window.addEventListener('mousemove', onMove);
    window.addEventListener('mouseup', onUp);
    canvas.addEventListener('wheel', onWheel, { passive: false });
    canvas.addEventListener('touchstart', onTouchStart, { passive: true });
    window.addEventListener('touchmove', onTouchMove, { passive: false });
    window.addEventListener('touchend', () => { dragging = false; });
    return true;
  }

  function resize() {
    const w = canvas.clientWidth, h = canvas.clientHeight;
    if (w === 0 || h === 0) return;
    camera.aspect = w / h;
    camera.updateProjectionMatrix();
    rendererGL.setSize(w, h, false);
  }

  function markInteracted() {
    userInteracted = true;
    if (idleTimer) clearTimeout(idleTimer);
    idleTimer = setTimeout(() => { userInteracted = false; }, 4000);
  }

  function onDown(e) { dragging = true; lastX = e.clientX; lastY = e.clientY; markInteracted(); }
  function onMove(e) {
    if (!dragging) return;
    const dx = e.clientX - lastX, dy = e.clientY - lastY;
    lastX = e.clientX; lastY = e.clientY;
    applyDrag(dx, dy);
  }
  function onUp() { dragging = false; }
  function onWheel(e) {
    e.preventDefault();
    markInteracted();
    camDistance *= (1 + e.deltaY * 0.001);
    camDistance = Math.max(1.6, Math.min(12, camDistance));
    camera.position.set(0, 0, camDistance);
  }
  let touchLast = null;
  function onTouchStart(e) { if (e.touches.length === 1) { touchLast = [e.touches[0].clientX, e.touches[0].clientY]; dragging = true; markInteracted(); } }
  function onTouchMove(e) {
    if (!dragging || e.touches.length !== 1) return;
    e.preventDefault();
    const dx = e.touches[0].clientX - touchLast[0], dy = e.touches[0].clientY - touchLast[1];
    touchLast = [e.touches[0].clientX, e.touches[0].clientY];
    applyDrag(dx, dy);
  }
  function applyDrag(dx, dy) {
    const qx = new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0, 1, 0), dx * 0.006);
    const qy = new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(1, 0, 0), dy * 0.006);
    orbitQuat.premultiply(qx).premultiply(qy);
    world.quaternion.copy(orbitQuat);
  }

  function autoRotateStep(dt) {
    if (!toggles.spin || userInteracted) return;
    const q = new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0, 1, 0), dt * 0.15);
    orbitQuat.premultiply(q);
    world.quaternion.copy(orbitQuat);
  }

  function faceCentroid(poly, f) {
    const c = new THREE.Vector3();
    for (const vi of f) c.add(poly.verts[vi]);
    return c.multiplyScalar(1 / f.length);
  }

  // Build a BufferGeometry (fan-triangulated) with a per-vertex color determined by
  // the size of the face it belongs to (a vertex touching only one face size gets
  // that color cleanly; shared verts get whichever face is drawn — fine since color
  // is meant to read at the face level and faces don't share triangulation verts here).
  function buildFaceGeometry(poly, isFullereneCtx, isolatedHexFaceIndices, explicitColors, forceRhombusQuads) {
    const positions = [];
    const colors = [];
    const normals = [];
    const colorObj = new THREE.Color();
    poly.faces.forEach((f, fi) => {
      if (f.length < 3) return;
      const col = explicitColors
        ? explicitColors[fi]
        : (FACE_COLORS[classifyFace(poly, f, fi, isFullereneCtx, isolatedHexFaceIndices, forceRhombusQuads)] || 0x999999);
      colorObj.setHex(col);
      const centroid = faceCentroid(poly, f);
      let normal = new THREE.Vector3();
      for (let i = 0; i < f.length; i++) {
        const p1 = poly.verts[f[i]], p2 = poly.verts[f[(i + 1) % f.length]];
        normal.add(new THREE.Vector3().crossVectors(p1, p2));
      }
      if (normal.lengthSq() < 1e-20) normal.copy(centroid).normalize(); else normal.normalize();
      for (let i = 0; i < f.length; i++) {
        const a = poly.verts[f[i]], b = poly.verts[f[(i + 1) % f.length]];
        positions.push(a.x, a.y, a.z, b.x, b.y, b.z, centroid.x, centroid.y, centroid.z);
        for (let k = 0; k < 3; k++) { colors.push(colorObj.r, colorObj.g, colorObj.b); normals.push(normal.x, normal.y, normal.z); }
      }
    });
    const geo = new THREE.BufferGeometry();
    geo.setAttribute('position', new THREE.Float32BufferAttribute(positions, 3));
    geo.setAttribute('color', new THREE.Float32BufferAttribute(colors, 3));
    geo.setAttribute('normal', new THREE.Float32BufferAttribute(normals, 3));
    return geo;
  }

  // highlightEdgeSet, if given, is a Set of "min_max" vertex-index-pair keys to exclude from
  // the normal edge lines (they're drawn separately, see buildHighlightEdgeGeometry) so the
  // highlight color isn't blended with/hidden under the regular edge color at the same spot.
  function buildEdgeGeometry(poly, highlightEdgeSet) {
    const positions = [];
    const seen = new Set();
    for (const f of poly.faces) {
      const n = f.length;
      for (let i = 0; i < n; i++) {
        const a = f[i], b = f[(i + 1) % n];
        const key = Math.min(a, b) + '_' + Math.max(a, b);
        if (seen.has(key)) continue;
        seen.add(key);
        if (highlightEdgeSet && highlightEdgeSet.has(key)) continue;
        const pa = poly.verts[a], pb = poly.verts[b];
        positions.push(pa.x, pa.y, pa.z, pb.x, pb.y, pb.z);
      }
    }
    const geo = new THREE.BufferGeometry();
    geo.setAttribute('position', new THREE.Float32BufferAttribute(positions, 3));
    return geo;
  }

  function buildHighlightEdgeGeometry(poly, highlightEdgeSet) {
    const positions = [];
    for (const key of highlightEdgeSet) {
      const [a, b] = key.split('_').map(Number);
      const pa = poly.verts[a], pb = poly.verts[b];
      positions.push(pa.x, pa.y, pa.z, pb.x, pb.y, pb.z);
    }
    const geo = new THREE.BufferGeometry();
    geo.setAttribute('position', new THREE.Float32BufferAttribute(positions, 3));
    return geo;
  }

  // highlightEdges (only meaningful in fullerene context): an array of [a,b] vertex-index
  // pairs to draw in magenta — marks a pentagon-pentagon adjacency edge in a "non-isolated
  // pentagons" isomer. isolatedHexFaceIndices (also fullerene-context only): a Set of indices
  // into poly.faces marking which hexagon faces are isolated ones, for the same highlight
  // treatment C(n) context always gives its (necessarily isolated) hexagon faces.
  let lastSetPolyArgs = null; // cached so the highlightIsolatedHex toggle can trigger a rebuild
  function setPoly(poly, poleIndices, isFullereneCtx, highlightEdges, isolatedHexFaceIndices, explicitColors, forceRhombusQuads) {
    lastSetPolyArgs = [poly, poleIndices, isFullereneCtx, highlightEdges, isolatedHexFaceIndices, explicitColors, forceRhombusQuads];
    if (faceMesh) { scene_disposeMesh(faceMesh); world.remove(faceMesh); faceMesh = null; }
    if (edgeLines) { scene_disposeMesh(edgeLines); world.remove(edgeLines); edgeLines = null; }
    if (highlightLines) { scene_disposeMesh(highlightLines); world.remove(highlightLines); highlightLines = null; }
    while (poleGroup.children.length) { const c = poleGroup.children.pop(); c.geometry.dispose(); c.material.dispose(); }

    const faceGeo = buildFaceGeometry(poly, isFullereneCtx, isolatedHexFaceIndices, explicitColors, forceRhombusQuads);
    // flatShading:true would recompute normals per-triangle via screen-space derivatives,
    // which visibly creases each face along its centroid-fan triangulation seams even when
    // the face is perfectly planar. We already supply one true face-normal per vertex, so
    // smooth shading (flatShading:false) reads it directly and renders every face uniformly.
    const faceMat = new THREE.MeshStandardMaterial({
      vertexColors: true, flatShading: false, roughness: 0.75, metalness: 0.02,
      side: THREE.DoubleSide
    });
    if (!toggles.color && !toggles.symmetryColor) faceMat.vertexColors = false, faceMat.color = new THREE.Color(0xb9a98e);
    faceMesh = new THREE.Mesh(faceGeo, faceMat);
    world.add(faceMesh);

    const highlightEdgeSet = (isFullereneCtx && highlightEdges && highlightEdges.length)
      ? new Set(highlightEdges.map(([a, b]) => Math.min(a, b) + '_' + Math.max(a, b)))
      : null;

    const edgeGeo = buildEdgeGeometry(poly, highlightEdgeSet);
    const edgeMat = new THREE.LineBasicMaterial({ color: EDGE_COLOR, transparent: true, opacity: 0.55 });
    edgeLines = new THREE.LineSegments(edgeGeo, edgeMat);
    edgeLines.visible = toggles.edges;
    world.add(edgeLines);

    if (highlightEdgeSet) {
      const highlightGeo = buildHighlightEdgeGeometry(poly, highlightEdgeSet);
      const highlightMat = new THREE.LineBasicMaterial({ color: EDGE_HIGHLIGHT_COLOR, linewidth: 3 });
      highlightLines = new THREE.LineSegments(highlightGeo, highlightMat);
      highlightLines.visible = toggles.edges;
      world.add(highlightLines);
    }

    if (poleIndices && poleIndices.length) {
      const poleGeo = new THREE.SphereGeometry(0.035, 12, 8);
      const poleMat = new THREE.MeshStandardMaterial({ color: POLE_COLOR, roughness: 0.5 });
      for (const idx of poleIndices) {
        const m = new THREE.Mesh(poleGeo, poleMat);
        m.position.copy(poly.verts[idx]);
        poleGroup.add(m);
      }
    }
    poleGroup.visible = toggles.poles;
  }

  // Symmetry-axis rods (Stella-style): one thin cylinder per distinct rotation axis,
  // long enough to poke out through the surface on both sides, colored by the same
  // colorForSymmetryRank priority the face-orbit coloring uses -- axesData entries
  // already carry the right `rank` (0 = highest rotation order present, e.g. the 5-fold
  // axes of an icosahedral solid), computed once by Geo.computeSymmetryAxes. Rebuilt
  // from scratch on every call rather than diffed -- cheap (at most a few dozen thin
  // cylinders) and this is only ever called on a settled poly, never per animation frame.
  function setAxes(poly, axesData) {
    while (axisGroup.children.length) { const c = axisGroup.children.pop(); c.geometry.dispose(); c.material.dispose(); }
    if (!poly || !axesData || !axesData.length) return;
    let maxR = 0;
    for (const v of poly.verts) maxR = Math.max(maxR, v.length());
    const rodLength = maxR * 2.6;
    const rodRadius = Math.max(0.006, maxR * 0.007);
    const up = new THREE.Vector3(0, 1, 0);
    for (const { axis, rank } of axesData) {
      const geo = new THREE.CylinderGeometry(rodRadius, rodRadius, rodLength, 10);
      const mat = new THREE.MeshBasicMaterial({ color: colorForSymmetryRank(rank) });
      const mesh = new THREE.Mesh(geo, mat);
      mesh.quaternion.setFromUnitVectors(up, axis);
      axisGroup.add(mesh);
    }
    axisGroup.visible = toggles.axes;
  }

  function scene_disposeMesh(obj) { if (obj.geometry) obj.geometry.dispose(); if (obj.material) obj.material.dispose(); }

  function setToggles(t) {
    const hexToggleChanged = 'highlightIsolatedHex' in t && t.highlightIsolatedHex !== toggles.highlightIsolatedHex;
    Object.assign(toggles, t);
    if (edgeLines) edgeLines.visible = toggles.edges;
    if (highlightLines) highlightLines.visible = toggles.edges;
    if (sphereMesh) sphereMesh.visible = toggles.sphere;
    if (poleGroup) poleGroup.visible = toggles.poles;
    if (axisGroup) axisGroup.visible = toggles.axes;
    if (faceMesh) {
      const colorsOn = toggles.color || toggles.symmetryColor;
      faceMesh.material.vertexColors = colorsOn;
      if (!colorsOn) faceMesh.material.color = new THREE.Color(0xb9a98e);
      faceMesh.material.needsUpdate = true;
    }
    // face colors for isolated hexagons are baked into the geometry, not a visibility flag,
    // so this toggle needs an actual rebuild rather than just flipping a material property.
    if (hexToggleChanged && lastSetPolyArgs) setPoly(...lastSetPolyArgs);
  }

  // Render an intermediate frame during the morph: same face list as `baseFaces`
  // (the fullerene's pentagon/hexagon faces) but vertex positions lerped toward
  // `targetPositions` (each fullerene vertex -> its pole's or its own target spot).
  function renderMorphFrame(baseFaces, fromPositions, targetPositions, t) {
    const n = fromPositions.length;
    const lerped = new Array(n);
    for (let i = 0; i < n; i++) lerped[i] = new THREE.Vector3().lerpVectors(fromPositions[i], targetPositions[i], t);
    setPoly({ verts: lerped, faces: baseFaces }, null, true);
  }

  // Expansion-style morph between a poly and its dual (Geo.computeDual's output): every
  // original face shrinks toward its one dual vertex (dualVerts[fi], since dual vertex fi is
  // dual to original face fi) while a new face grows at every original vertex out to the dual
  // vertices around it (dualFaces[v]), and a third "wall" face opens up along every original
  // edge to close the gap the first two leave behind. A face corner is identified by the pair
  // (face index, vertex index) — corner(fi, vi) = lerp(poly.verts[vi], dualVerts[fi], t) — and
  // that single formula is exactly the point needed by all three face families (a shrinking
  // face's corner, the matching corner of the growing face at that vertex, and two corners of
  // each wall quad), so each one is computed once and shared by reference instead of
  // duplicated. At t=0 the shrinking faces reconstruct the original poly exactly and the
  // growing/wall faces are all degenerate (zero area, invisible); at t=1 it's the reverse.
  function buildTruncationMorphPoly(poly, dualVerts, dualFaces, t) {
    const verts = [];
    const faces = [];
    const corner = new Map(); // `${fi}_${vi}` -> index into verts
    const edgeFace = new Map(); // `${a}_${b}` (directed) -> fi, for the wall-quad pass below

    poly.faces.forEach((f, fi) => {
      const n = f.length;
      const target = dualVerts[fi];
      const faceCorners = new Array(n);
      for (let i = 0; i < n; i++) {
        const vi = f[i];
        verts.push(poly.verts[vi].clone().lerp(target, t));
        const idx = verts.length - 1;
        corner.set(fi + '_' + vi, idx);
        faceCorners[i] = idx;
      }
      faces.push(faceCorners);
      for (let i = 0; i < n; i++) edgeFace.set(f[i] + '_' + f[(i + 1) % n], fi);
    });
    const numShrink = faces.length;

    const growVertexOf = [];
    for (let v = 0; v < poly.verts.length; v++) {
      const fan = dualFaces[v];
      if (!fan || !fan.length) continue;
      faces.push(fan.map(fi => corner.get(fi + '_' + v)));
      growVertexOf.push(v);
    }
    const numGrow = faces.length - numShrink;

    const seenEdges = new Set();
    poly.faces.forEach(f => {
      const n = f.length;
      for (let i = 0; i < n; i++) {
        const a = f[i], b = f[(i + 1) % n];
        const key = Math.min(a, b) + '_' + Math.max(a, b);
        if (seenEdges.has(key)) continue;
        seenEdges.add(key);
        const f1 = edgeFace.get(a + '_' + b), f2 = edgeFace.get(b + '_' + a);
        if (f1 == null || f2 == null) continue; // open boundary edge — shouldn't occur here
        faces.push([corner.get(f1 + '_' + a), corner.get(f1 + '_' + b),
                     corner.get(f2 + '_' + b), corner.get(f2 + '_' + a)]);
      }
    });

    return { verts, faces, numShrink, numGrow, growVertexOf };
  }

  // Colors for a morph frame, precomputed once per toggle (not per animation frame — shape
  // classification depends only on which face a corner belongs to, never on t): shrinking
  // faces are classified exactly as the static base view would (same isFullereneCtx /
  // isolatedHexFaceIndices), growing faces are classified exactly as the static dual view
  // would (isFullereneCtx=false, using the dual's own verts/faces so quad shape checks read
  // the true end-state proportions rather than a mid-morph distortion), and wall quads get a
  // fixed neutral color since they're a rendering necessity, not a face of either polyhedron.
  function buildMorphFaceColors(poly, dualVerts, dualFaces, built, isFullereneCtx, isolatedHexFaceIndices, forceRhombusQuads) {
    const colors = new Array(built.faces.length);
    let fi = 0;
    for (; fi < built.numShrink; fi++) {
      colors[fi] = FACE_COLORS[classifyFace(poly, poly.faces[fi], fi, isFullereneCtx, isolatedHexFaceIndices)] || 0x999999;
    }
    const dualLike = { verts: dualVerts };
    for (let g = 0; g < built.numGrow; g++, fi++) {
      const v = built.growVertexOf[g];
      colors[fi] = FACE_COLORS[classifyFace(dualLike, dualFaces[v], v, false, null, forceRhombusQuads)] || 0x999999;
    }
    for (; fi < built.faces.length; fi++) colors[fi] = EDGE_QUAD_COLOR;
    return colors;
  }

  function renderDualMorphFrame(poly, dualVerts, dualFaces, t, isFullereneCtx, isolatedHexFaceIndices, forceRhombusQuads) {
    const built = buildTruncationMorphPoly(poly, dualVerts, dualFaces, t);
    const colors = buildMorphFaceColors(poly, dualVerts, dualFaces, built, isFullereneCtx, isolatedHexFaceIndices, forceRhombusQuads);
    setPoly(built, null, false, null, null, colors);
  }

  function render() {
    rendererGL.render(scene, camera);
  }

  function startLoop(onFrame) {
    let last = performance.now();
    function tick(now) {
      const dt = Math.min(0.05, (now - last) / 1000);
      last = now;
      resize();
      autoRotateStep(dt);
      if (onFrame) onFrame(dt);
      render();
      requestAnimationFrame(tick);
    }
    requestAnimationFrame(tick);
  }

  global.Renderer = { init, setPoly, setAxes, setToggles, renderMorphFrame, renderDualMorphFrame, startLoop, resize, FACE_COLORS, colorForSymmetryRank };
})(window);
