# One-off conversion: off_data/oct_like_catalan-like_*.off -> oct_data.js
# Mirrors the format of catalan_data.js (window.CATALAN_TABLE) but for the
# octahedral-symmetry admissible solutions (window.OCT_TABLE). Run manually
# whenever off_data/oct_like_catalan-like_*.off changes; not part of any build step.

$offDir = Join-Path $PSScriptRoot "..\off_data"
$outFile = Join-Path $PSScriptRoot "..\oct_data.js"

$files = Get-ChildItem -Path $offDir -Filter "oct_like_catalan-like_*.off" | Sort-Object {
    [int]([regex]::Match($_.Name, '(\d+)').Value)
}

$entries = @()
foreach ($f in $files) {
    $n = [int]([regex]::Match($f.Name, '(\d+)').Value)
    $lines = Get-Content -Path $f.FullName
    $lines = $lines | Where-Object { $_.Trim().Length -gt 0 }
    if ($lines[0].Trim() -ne "OFF") { throw "$($f.Name): expected OFF header" }
    $counts = $lines[1].Trim() -split '\s+'
    $nv = [int]$counts[0]
    $nf = [int]$counts[1]

    $verts = @()
    for ($i = 0; $i -lt $nv; $i++) {
        $parts = $lines[2 + $i].Trim() -split '\s+'
        $verts += ("[" + $parts[0] + "," + $parts[1] + "," + $parts[2] + "]")
    }

    $faces = @()
    for ($i = 0; $i -lt $nf; $i++) {
        $parts = $lines[2 + $nv + $i].Trim() -split '\s+'
        $k = [int]$parts[0]
        $idx = $parts[1..$k]
        $faces += ("[" + ($idx -join ",") + "]")
    }

    $entry = '"' + $n + '":{"nv":' + $nv + ',"verts":[' + ($verts -join ",") + '],"faces":[' + ($faces -join ",") + ']}'
    $entries += $entry
}

$js = @()
$js += "// Vertex coordinates + face lists for octahedral-symmetry C(n) admissible solutions."
$js += "// Generated by scripts/convert_oct_off.ps1 from off_data/oct_like_catalan-like_*.off."
$js += "// These are the contracted Catalan-like solids directly (quad poles, degree 4) --"
$js += "// no underlying raw-fullerene reconstruction data is available yet."
$js += ("window.OCT_TABLE = {" + ($entries -join ",") + "};")

Set-Content -Path $outFile -Value ($js -join "`n") -Encoding utf8 -NoNewline
Write-Host "Wrote $outFile with $($entries.Count) entries."
